[project]
name = "sqlite-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "nb-tokenizer>=0.1.0",
    "pandas>=2.3.3",
]
